[project]
name = "chess-vlm"
version = "0.1.0"
description = "A toy analysis of the visual reasoning priors of VLMs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fentoboardimage>=0.5",
    "vllm>=0.11.0",
]
